name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: Bhupesh-V/memer-action@master
        with:
          filter: new

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.meme }}"
          echo "${{ steps.selftest.outputs.title }}"
          echo "${{ steps.selftest.outputs.source }}"
